# Generated by Django 5.2.1 on 2025-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_extractedresume_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedresume',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='cualidades_personales',
            field=models.TextField(blank=True, help_text='Ejemplo: Responsable, puntual, trabajo en equipo', null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('O', 'Otro'), ('P', 'Prefiero no decirlo')], default='P', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='habilidades_tecnicas',
            field=models.TextField(blank=True, help_text='Ejemplo: Python, SQL, Redes', null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='idiomas',
            field=models.TextField(blank=True, help_text='Ejemplo: Español nativo, Inglés B1', null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedresume',
            name='trabajo_deseado',
            field=models.CharField(blank=True, help_text='Ejemplo: Desarrollador backend en Python', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedresume',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedresume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
