# Generated by Django 5.1.7 on 2025-03-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_info', to='cv_forms.personalinfo'),
        ),
    ]
