# Generated by Django 5.1.7 on 2025-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_forms', '0003_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('O', 'Otro'), ('P', 'Prefiero no decirlo')], default='P', max_length=2),
        ),
    ]
